language: python

install:
  - pip install tox coveralls
matrix:
  include:
    - python: 3.8
      env:
          - ENV=docs
    - python: 3.5
      env:
          - ENV=py35-django20,py35-django21,py35-django22
    - python: 3.6
      env:
          - ENV=py36-django20,py36-django21,py36-django22,py36-django30,py36-django31,py36-django32
    - python: 3.7
      env:
          - ENV=py37-django20,py37-django21,py37-django22,py37-django30,py37-django31,py37-django32
    - python: 3.8
      env:
          - ENV=py38-django20,py38-django21,py38-django22,py38-django30,py38-django31,py38-django32
    - python: 3.9
      env:
          - ENV=py39-django20,py39-django21,py39-django22,py39-django30,py39-django31,py39-django32
    
script:
  - tox -e $ENV
after_success:
  - coveralls
