# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-16 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oidc_provider", "0001_initial"),
        swapper.dependency('oidc_provider', 'Code'),
        swapper.dependency('oidc_provider', 'Token'),
        swapper.dependency('oidc_provider', 'UserConsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('nonce', models.CharField(blank=True, default='', max_length=255, verbose_name='Nonce')),
                ('is_authentication', models.BooleanField(default=False, verbose_name='Is Authentication?')),
                ('code_challenge', models.CharField(max_length=255, null=True, verbose_name='Code Challenge')),
                ('code_challenge_method', models.CharField(max_length=255, null=True, verbose_name='Code Challenge Method')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'verbose_name_plural': 'Authorization Codes',
                'abstract': False,
                'swappable': swapper.swappable_setting('oidc_provider', 'Code'),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('access_token', models.CharField(max_length=255, unique=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=255, unique=True, verbose_name='Refresh Token')),
                ('_id_token', models.TextField(verbose_name='ID Token')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
                'swappable': swapper.swappable_setting('oidc_provider', 'Token'),
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('date_given', models.DateTimeField(verbose_name='Date Given')),
            ],
            options={
                'abstract': False,
                'swappable': swapper.swappable_setting('oidc_provider', 'UserConsent'),
            },
        ),
        migrations.AddField(
            model_name='userconsent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_provider_userconsent_set', to='oidc_provider.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_provider_userconsent_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='token',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_provider_token_set', to='oidc_provider.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oidc_provider_token_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='code',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_provider_code_set', to='oidc_provider.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='code',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_provider_code_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together=set([('user', 'client')]),
        ),
    ]
