# Generated by Django 2.2.14 on 2021-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0034_add_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='force_consent',
            field=models.BooleanField(default=False, help_text='If enabled, the consent of the user is forced and skips the consent step.', verbose_name='Force Consent?'),
        ),
    ]
