# Generated by Django 4.2.23 on 2025-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0034_add_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_secret_encrypted',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='code',
            name='code_encrypted',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='access_token_encrypted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='refresh_token_encrypted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
