# Generated by Django 4.2.23 on 2025-09-10 20:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_provider", "0034_add_issued_at"),
    ]

    operations = [
        # Make unencrypted fields nullable to allow smooth transition
        migrations.AlterField(
            model_name="client",
            name="client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rsakey",
            name="key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        # Move the unencrypted fields to *_old
        migrations.RenameField(
            model_name="client",
            old_name="client_secret",
            new_name="client_secret_old",
        ),
        migrations.RenameField(
            model_name="token",
            old_name="access_token",
            new_name="access_token_old",
        ),
        migrations.RenameField(
            model_name="token",
            old_name="refresh_token",
            new_name="refresh_token_old",
        ),
        migrations.RenameField(
            model_name="rsakey",
            old_name="key",
            new_name="key_old",
        ),
        # Add the new encrypted fields (they will be populated in the next migration)
        migrations.AddField(
            model_name="client",
            name="client_secret",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rsakey",
            name="key",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="access_token",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="refresh_token",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
