# Generated by Django 4.2.23 on 2025-09-10 19:44

from django.db import migrations


def plaintext_dict(value):
    return {"kid": "plaintext", "alg": "plaintext", "ciphertext": value}


def forward_func(apps, schema_editor):
    Client = apps.get_model("oidc_provider", "Client")
    Token = apps.get_model("oidc_provider", "Token")
    RSAKey = apps.get_model("oidc_provider", "RSAKey")

    for client in Client.objects.all():
        client.client_secret = plaintext_dict(client.client_secret_old)
        client.save(update_fields=["client_secret"])
    for token in Token.objects.all():
        token.access_token = plaintext_dict(token.access_token_old)
        token.refresh_token = plaintext_dict(token.refresh_token_old)
        token.save(update_fields=["access_token", "refresh_token"])
    for rsakey in RSAKey.objects.all():
        rsakey.key = plaintext_dict(rsakey.key_old)
        rsakey.save(update_fields=["key"])


def plaintext(value):
    if value is None:
        return None
    if isinstance(value, dict) and value.get("alg") == "plaintext":
        return value.get("ciphertext", "")
    # NOTE: We cannot handle non-plaintext values here. As a preperation to migrating
    #       backwards here, it is necessary to first rollover all values to the
    #       plaintext cipher.
    raise ValueError(f"Value '{value}' is not plaintext, can't migrate")


def reverse_func(apps, schema_editor):
    Client = apps.get_model("oidc_provider", "Client")
    Token = apps.get_model("oidc_provider", "Token")
    RSAKey = apps.get_model("oidc_provider", "RSAKey")
    for client in Client.objects.all():
        client.client_secret_old = plaintext(client.client_secret)
        client.save(update_fields=["client_secret_old"])
    for token in Token.objects.all():
        token.access_token_old = plaintext(token.access_token)
        token.refresh_token_old = plaintext(token.refresh_token)
        token.save(update_fields=["access_token_old", "refresh_token_old"])
    for rsakey in RSAKey.objects.all():
        rsakey.key_old = plaintext(rsakey.key)
        rsakey.save(update_fields=["key_old"])


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_provider", "0035_encrypted_fields_part_1_of_3"),
    ]

    operations = [
        migrations.RunPython(code=forward_func, reverse_code=reverse_func),
    ]
