# Generated by Django 4.2.23 on 2025-09-10 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_provider", "0036_encrypted_fields_part_2_of_3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_secret_old",
        ),
        migrations.RemoveField(
            model_name="rsakey",
            name="key_old",
        ),
        migrations.RemoveField(
            model_name="token",
            name="access_token_old",
        ),
        migrations.RemoveField(
            model_name="token",
            name="refresh_token_old",
        ),
    ]
