name: tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django: [
          "django>=2.0,<2.1",
          "django>=2.1,<2.2",
          "django>=2.2,<3.0",
          "django>=3.0,<3.1",
          "django>=3.1,<3.2",
          "django>=3.2,<4.0",
          "django>=4.0,<4.1",
          "django>=4.1,<4.2",
          "django>=4.2,<5.0",
        ]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
          # django 2.0
          - django: "django>=2.0,<2.1"
            python: "3.8"
          - django: "django>=2.0,<2.1"
            python: "3.9"
          - django: "django>=2.0,<2.1"
            python: "3.10"
          - django: "django>=2.0,<2.1"
            python: "3.11"
          - django: "django>=2.0,<2.1"
            python: "3.12"
          # django 2.1
          - django: "django>=2.1,<2.2"
            python: "3.4"
          - django: "django>=2.1,<2.2"
            python: "3.8"
          - django: "django>=2.1,<2.2"
            python: "3.9"
          - django: "django>=2.1,<2.2"
            python: "3.10"
          - django: "django>=2.1,<2.2"
            python: "3.11"
          - django: "django>=2.1,<2.2"
            python: "3.12"
          # django 2.2
          - django: "django>=2.2,<3.0"
            python: "3.4"
          - django: "django>=2.2,<3.0"
            python: "3.10"
          - django: "django>=2.2,<3.0"
            python: "3.11"
          - django: "django>=2.2,<3.0"
            python: "3.12"
          # django 3.0
          - django: "django>=3.0,<3.1"
            python: "3.4"
          - django: "django>=3.0,<3.1"
            python: "3.5"
          - django: "django>=3.0,<3.1"
            python: "3.10"
          - django: "django>=3.0,<3.1"
            python: "3.11"
          - django: "django>=3.0,<3.1"
            python: "3.12"
          # django 3.1
          - django: "django>=3.1,<3.2"
            python: "3.4"
          - django: "django>=3.1,<3.2"
            python: "3.5"
          - django: "django>=3.1,<3.2"
            python: "3.10"
          - django: "django>=3.1,<3.2"
            python: "3.11"
          - django: "django>=3.1,<3.2"
            python: "3.12"
          # django 3.2
          - django: "django>=3.2,<4.0"
            python: "3.4"
          - django: "django>=3.2,<4.0"
            python: "3.5"
          - django: "django>=3.2,<4.0"
            python: "3.11"
          - django: "django>=3.2,<4.0"
            python: "3.12"
          # django 4.0
          - django: "django>=4.0,<4.1"
            python: "3.4"
          - django: "django>=4.0,<4.1"
            python: "3.5"
          - django: "django>=4.0,<4.1"
            python: "3.6"
          - django: "django>=4.0,<4.1"
            python: "3.7"
          - django: "django>=4.0,<4.1"
            python: "3.11"
          - django: "django>=4.0,<4.1"
            python: "3.12"
          # django 4.1
          - django: "django>=4.1,<4.2"
            python: "3.4"
          - django: "django>=4.1,<4.2"
            python: "3.5"
          - django: "django>=4.1,<4.2"
            python: "3.6"
          - django: "django>=4.1,<4.2"
            python: "3.7"
          - django: "django>=4.1,<4.2"
            python: "3.12"
          # django 4.2
          - django: "django>=4.2,<5.0"
            python: "3.4"
          - django: "django>=4.2,<5.0"
            python: "3.5"
          - django: "django>=4.2,<5.0"
            python: "3.6"
          - django: "django>=4.2,<5.0"
            python: "3.7"

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install dependencies
        run: |
          pip install mock psycopg2-binary pytest pytest-django pytest-flake8 pytest-cov
          pip install "${{ matrix.django }}"
          pip install -e .
      - name: run tests
        run: |
          cd oidc_provider
          pytest -v tests/ --cov=oidc_provider
